import { Flame, Zap, Shield, Globe, Bot, UserCheck, Clock, Sparkles } from 'lucide-react';

const About = () => {
  const features = [
    {
      icon: <Bot className="w-7 h-7" />,
      title: "AI-Powered Roasts",
      description: "Harnessing the power of Llama 4 and Groq API, our advanced AI scans website metadata and content to deliver highly accurate, brutally honest, and savage critiques.",
      color: "blue"
    },
    {
      icon: <Globe className="w-7 h-7" />,
      title: "Multi-Language Translation",
      description: "Why get roasted only in English? Instantly translate any roast into Spanish, French, German, Tamil, Hindi, or Japanese with a single click.",
      color: "indigo"
    },
    {
      icon: <UserCheck className="w-7 h-7" />,
      title: "Secure User Accounts",
      description: "Create an account to unlock the full power of Link Roaster. Your data is protected with industry-standard encryption and JWT authentication.",
      color: "pink"
    },
    {
      icon: <Clock className="w-7 h-7" />,
      title: "Personal History",
      description: "Never lose a good roast. All your roasted links are safely stored in your personal History dashboard so you can revisit them anytime.",
      color: "purple"
    },
    {
      icon: <Flame className="w-7 h-7" />,
      title: "Global Recent Feed",
      description: "Discover the internet's most questionable websites by browsing the live recent feed of roasts generated by other users across the globe.",
      color: "orange"
    },
    {
      icon: <Zap className="w-7 h-7" />,
      title: "Instant Insights",
      description: "Get a breakdown of what works, what doesn't, and what's completely overhyped about any URL in a matter of seconds. No sugarcoating allowed.",
      color: "yellow"
    }
  ];

  const getColorClasses = (color) => {
    const classes = {
      blue: "bg-blue-50 text-[#0A66C2] group-hover:bg-[#0A66C2] group-hover:text-white",
      indigo: "bg-indigo-50 text-indigo-600 group-hover:bg-indigo-600 group-hover:text-white",
      pink: "bg-pink-50 text-pink-600 group-hover:bg-pink-600 group-hover:text-white",
      purple: "bg-purple-50 text-purple-600 group-hover:bg-purple-600 group-hover:text-white",
      orange: "bg-orange-50 text-orange-600 group-hover:bg-orange-600 group-hover:text-white",
      yellow: "bg-yellow-50 text-yellow-600 group-hover:bg-yellow-600 group-hover:text-white"
    };
    return classes[color] || classes.blue;
  };

  return (
    <div className="relative min-h-screen overflow-hidden bg-[#F3F2EF] py-16 md:py-24">
      {/* Animated Background Blobs */}
      <div className="absolute top-0 -left-4 w-96 h-96 bg-blue-300 rounded-full mix-blend-multiply filter blur-3xl opacity-50 animate-blob pointer-events-none"></div>
      <div className="absolute top-0 -right-4 w-96 h-96 bg-indigo-300 rounded-full mix-blend-multiply filter blur-3xl opacity-50 animate-blob animation-delay-2000 pointer-events-none"></div>
      <div className="absolute -bottom-8 left-1/2 w-96 h-96 bg-pink-300 rounded-full mix-blend-multiply filter blur-3xl opacity-50 animate-blob animation-delay-4000 pointer-events-none"></div>

      <div className="relative container mx-auto px-4 max-w-7xl z-10">
        
        {/* Header Section */}
        <div className="text-center mb-20">
          <div className="inline-block mb-6 px-5 py-2 rounded-full bg-white border border-gray-200 text-[#0A66C2] text-sm font-bold tracking-widest uppercase animate-float-delayed shadow-sm">
            <span className="flex items-center gap-2">
              <Sparkles className="w-4 h-4" />
              Inside Link Roaster
            </span>
          </div>
          <h1 className="text-5xl md:text-7xl font-black text-transparent bg-clip-text bg-gradient-to-r from-gray-900 via-[#0A66C2] to-indigo-600 mb-6 tracking-tight animate-glow pb-2">
            Professional Grade.<br className="hidden md:block" />
            <span className="text-[#0A66C2]">Brutally Honest.</span>
          </h1>
          <p className="text-[#666666] max-w-3xl mx-auto text-xl md:text-2xl leading-relaxed font-medium">
            Link Roaster is not just an insult generator. It's a sophisticated AI-powered tool designed to tear down the internet's worst UI/UX, questionable content, and overhyped marketing.
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <div 
              key={index} 
              className="glass-panel p-8 rounded-2xl hover:-translate-y-2 hover:shadow-2xl hover:border-blue-200 transition-all duration-300 group bg-white/60 backdrop-blur-md border border-white/50"
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              <div className={`w-14 h-14 rounded-xl flex items-center justify-center mb-6 group-hover:scale-110 transition-all duration-300 shadow-sm ${getColorClasses(feature.color)}`}>
                {feature.icon}
              </div>
              <h3 className="text-xl font-extrabold mb-3 text-gray-900 tracking-tight">{feature.title}</h3>
              <p className="text-[#434649] leading-relaxed text-base">{feature.description}</p>
            </div>
          ))}
        </div>

        {/* Bottom CTA / Banner */}
        <div className="mt-24 max-w-5xl mx-auto glass-panel p-10 md:p-14 rounded-3xl bg-gradient-to-br from-indigo-900 to-[#0A66C2] text-white text-center shadow-2xl relative overflow-hidden group">
          {/* Decorative background overlay */}
          <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10 mix-blend-overlay"></div>
          
          <div className="relative z-10">
            <h2 className="text-3xl md:text-5xl font-bold mb-6 tracking-tight">Ready to feel the burn?</h2>
            <p className="text-indigo-100 text-lg md:text-xl mb-10 max-w-2xl mx-auto leading-relaxed">
              Join thousands of users discovering the ugly truth about their favorite websites. Sign up today and start roasting.
            </p>
            <a 
              href="/"
              className="inline-flex items-center gap-2 bg-white text-[#0A66C2] px-8 py-4 rounded-full font-bold text-lg hover:bg-gray-50 hover:scale-105 transition-all shadow-xl"
            >
              <Flame className="w-5 h-5" />
              Start Roasting Now
            </a>
          </div>
        </div>

      </div>
    </div>
  );
};

export default About;
