import { Flame, Zap, Shield, Globe, Bot, UserCheck, Clock, Sparkles } from 'lucide-react';

const About = () => {
  const features = [
    {
      icon: <Bot className="w-7 h-7" />,
      title: "AI-Powered Roasts",
      description: "Harnessing the power of Llama 4 and Groq API, our advanced AI scans website metadata and content to deliver highly accurate, brutally honest, and savage critiques.",
      color: "blue"
    },
    {
      icon: <Globe className="w-7 h-7" />,
      title: "Multi-Language Translation",
      description: "Why get roasted only in English? Instantly translate any roast into Spanish, French, German, Tamil, Hindi, or Japanese with a single click.",
      color: "indigo"
    },
    {
      icon: <UserCheck className="w-7 h-7" />,
      title: "Secure User Accounts",
      description: "Create an account to unlock the full power of Link Roaster. Your data is protected with industry-standard encryption and JWT authentication.",
      color: "pink"
    },
    {
      icon: <Clock className="w-7 h-7" />,
      title: "Personal History",
      description: "Never lose a good roast. All your roasted links are safely stored in your personal History dashboard so you can revisit them anytime.",
      color: "purple"
    },
    {
      icon: <Flame className="w-7 h-7" />,
      title: "Global Recent Feed",
      description: "Discover the internet's most questionable websites by browsing the live recent feed of roasts generated by other users across the globe.",
      color: "orange"
    },
    {
      icon: <Zap className="w-7 h-7" />,
      title: "Instant Insights",
      description: "Get a breakdown of what works, what doesn't, and what's completely overhyped about any URL in a matter of seconds. No sugarcoating allowed.",
      color: "yellow"
    }
  ];

  const getColorClasses = (color) => {
    const classes = {
      blue: "bg-blue-50 text-[#0A66C2] group-hover:bg-[#0A66C2] group-hover:text-white",
      indigo: "bg-indigo-50 text-indigo-600 group-hover:bg-indigo-600 group-hover:text-white",
      pink: "bg-pink-50 text-pink-600 group-hover:bg-pink-600 group-hover:text-white",
      purple: "bg-purple-50 text-purple-600 group-hover:bg-purple-600 group-hover:text-white",
      orange: "bg-orange-50 text-orange-600 group-hover:bg-orange-600 group-hover:text-white",
      yellow: "bg-yellow-50 text-yellow-600 group-hover:bg-yellow-600 group-hover:text-white"
    };
    return classes[color] || classes.blue;
  };

  return (
    <div className="relative min-h-screen overflow-hidden bg-[#F3F2EF] py-16 md:py-24">
      {/* Animated Background Blobs */}
      <div className="absolute top-[-10%] left-[-10%] w-[40rem] h-[40rem] bg-gradient-to-br from-blue-400 to-cyan-300 rounded-full mix-blend-multiply filter blur-3xl opacity-40 animate-blob pointer-events-none"></div>
      <div className="absolute top-[20%] right-[-10%] w-[35rem] h-[35rem] bg-gradient-to-bl from-indigo-400 to-purple-400 rounded-full mix-blend-multiply filter blur-3xl opacity-40 animate-blob animation-delay-2000 pointer-events-none"></div>
      <div className="absolute bottom-[-20%] left-[20%] w-[45rem] h-[45rem] bg-gradient-to-tr from-pink-400 to-rose-300 rounded-full mix-blend-multiply filter blur-3xl opacity-30 animate-blob animation-delay-4000 pointer-events-none"></div>

      <div className="relative container mx-auto px-4 max-w-7xl z-10">
        
        {/* Header Section */}
        <div className="text-center mb-24">
          <div className="inline-block mb-8 px-6 py-2.5 rounded-full bg-white/80 backdrop-blur-md border border-white/50 text-[#0A66C2] text-sm font-bold tracking-widest uppercase animate-float-delayed shadow-lg shadow-blue-500/10 hover:shadow-blue-500/20 transition-all cursor-default">
            <span className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-blue-500" />
              Inside Link Roaster
            </span>
          </div>
          <h1 className="text-6xl md:text-8xl font-black text-transparent bg-clip-text bg-gradient-to-r from-gray-900 via-blue-700 to-indigo-800 mb-8 tracking-tighter animate-fade-in-up drop-shadow-sm pb-2">
            Professional Grade.<br className="hidden md:block" />
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-cyan-400">Brutally Honest.</span>
          </h1>
          <p className="text-gray-600 max-w-4xl mx-auto text-2xl md:text-3xl leading-relaxed font-medium animate-fade-in-up" style={{ animationDelay: '0.2s' }}>
            Not just an insult generator. A sophisticated AI-powered tool designed to tear down the internet's worst UI/UX, questionable content, and overhyped marketing.
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-10">
          {features.map((feature, index) => (
            <div 
              key={index} 
              className="glass-panel p-10 rounded-[2rem] hover:-translate-y-3 hover:shadow-2xl hover:shadow-blue-500/20 hover:border-blue-300 transition-all duration-500 group bg-white/70 backdrop-blur-xl border border-white/60 relative overflow-hidden"
              style={{ animationDelay: `${index * 0.15}s` }}
            >
              <div className="absolute -right-10 -top-10 w-40 h-40 bg-gradient-to-br from-white/40 to-transparent rounded-full mix-blend-overlay group-hover:scale-150 transition-transform duration-700"></div>
              
              <div className={`w-16 h-16 rounded-2xl flex items-center justify-center mb-8 group-hover:scale-110 group-hover:rotate-3 transition-all duration-300 shadow-md ${getColorClasses(feature.color)} relative z-10`}>
                {feature.icon}
              </div>
              <h3 className="text-2xl font-black mb-4 text-gray-900 tracking-tight relative z-10">{feature.title}</h3>
              <p className="text-gray-600 leading-relaxed text-lg relative z-10 font-medium">{feature.description}</p>
            </div>
          ))}
        </div>

        {/* Bottom CTA / Banner */}
        <div className="mt-24 max-w-5xl mx-auto glass-panel p-10 md:p-14 rounded-3xl bg-gradient-to-br from-indigo-900 to-[#0A66C2] text-white text-center shadow-2xl relative overflow-hidden group">
          {/* Decorative background overlay */}
          <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10 mix-blend-overlay"></div>
          
          <div className="relative z-10">
            <h2 className="text-3xl md:text-5xl font-bold mb-6 tracking-tight">Ready to feel the burn?</h2>
            <p className="text-indigo-100 text-lg md:text-xl mb-10 max-w-2xl mx-auto leading-relaxed">
              Join thousands of users discovering the ugly truth about their favorite websites. Sign up today and start roasting.
            </p>
            <a 
              href="/"
              className="inline-flex items-center gap-2 bg-white text-[#0A66C2] px-8 py-4 rounded-full font-bold text-lg hover:bg-gray-50 hover:scale-105 transition-all shadow-xl"
            >
              <Flame className="w-5 h-5" />
              Start Roasting Now
            </a>
          </div>
        </div>

      </div>
    </div>
  );
};

export default About;
